version: "3.8"

services:
  web-service:
    image: web-service
    build:
      context: ./
      dockerfile: .
    environment:
      - JAVA_OPTS=-Xmx256M
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-service
    ports:
      - "5000:5000"

#docker-compose up --scale web-service=3 //to run 3 instances of service accessible only through LB
